name: digi_store
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  flutter_screenutil: ^5.6.0
  image_picker:
  image_cropper: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  blurry_modal_progress_hud: ^1.0.3
  flutter_spinkit: ^5.1.0
  light_carousel: ^0.0.4
  readmore: ^2.2.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
